# linear and angular speed limits for the robot
# max_v: 0.2 #0.4 # m/s
# max_w: 0.15 #0.6 # rad/s

# max_v: 0.2  for tracer # m/s
# max_w: 0.15 for tracer # rad/s

# max_v: 0.30
max_v: 0.2
max_w: 0.15

# observation rate fo the robot
frame_rate: 15 # Hz
# frame_rate: 15 # Hz
graph_rate: 0.3333 # Hz  

# topic names (modify for different robots/nodes)
vel_teleop_topic: /cmd_vel_mux/input/teleop 
vel_navi_topic: /cmd_vel_mux/input/navi
# vel_navi_topic: /cmd_vel
vel_recovery_topic: /cmd_vel_mux/input/recovery


